### ISSUE TITLE
RoboRock S6 Fan mode not "translated"

### ISSUE THREAD

**Issue by freemann** [benct/lovelace-xiaomi-vacuum-card#21] opened 2019-11-08 09:47 UTC
The card is not  "translating" the fan mode code of the S6 to readable/understandable text, see screenshot;
![Screenshot - 08_11_2019 , 10_44_35](https://user-images.githubusercontent.com/601053/68466574-f4ed1100-0214-11ea-9b9d-e725bb61a6f1.png)

Codes are:
101: "Quiet"
102: "Balanced"
103: "Turbo"
104: "Max"

**Comment by tribut** [comment] 2019-11-08 13:06
This appears to be a duplicate of https://github.com/rytilahti/python-miio/pull/468 (see also https://github.com/home-assistant/home-assistant/issues/17695 and https://github.com/rytilahti/python-miio/pull/523).

**Comment by benct** [comment] 2019-11-08 14:00
As this seems to be a (soon-to-be-fixed?) bug in the xiaomi/miio integration itself, I will not be handling this in the lovelace card.

**Closed by benct** 2019-11-08 14:00 UTC
Labels: duplicate, wontfix

**Comment by hanseandersson** [comment] 2020-01-27 21:40
So this is closed but it's still a problem..?
How can I change so it changes in percent instead?

**Comment by benct** [comment] 2020-01-30 11:27
As mentioned in my last comment, this is not a bug in this card but a bug in the miio (Xiaomi) vacuum **integration** itself. See the links that @tribut posted in his comment further up, and comment on those issues instead :)
